// AUTO-GENERATED by scripts/genStepValues.test.ts — do not edit by hand.
// Grounds library step `variables` in real execution (see that script).
// Regenerate: GEN_STEP_VALUES=1 npx vitest run scripts/genStepValues.test.ts
import type { CodeExample } from "../types/algorithm";

export type GeneratedStepValues = Record<
  string,
  Partial<Record<CodeExample["language"], (Record<string, string> | null)[]>>
>;

export const GENERATED_STEP_VALUES: GeneratedStepValues = {
  "SRT_001": {
    "typescript": [
      null,
      null,
      null,
      {
        "left": "[]",
        "middle": "[]",
        "right": "[]"
      },
      null,
      null,
      null
    ]
  },
  "SRT_002": {
    "typescript": [
      null,
      null,
      null,
      {
        "left": "[2]",
        "right": "[8]"
      },
      null,
      {
        "left[i]": "2",
        "right[j]": "8",
        "result": "[]"
      },
      {
        "result": "[2]"
      }
    ],
    "python": [
      null,
      null,
      null,
      {
        "left": "[2]",
        "right": "[8]"
      },
      null,
      {
        "left[i]": "2",
        "right[j]": "8",
        "result": "[]"
      },
      {
        "result": "[2]"
      }
    ]
  },
  "SRT_003": {
    "typescript": [
      null,
      null,
      {
        "i": "5",
        "arr[0]": "9",
        "arr[i]": "7 (last)"
      },
      null,
      null,
      {
        "arr[i]": "3",
        "arr[left]": "5",
        "arr[right]": "8",
        "largest": "0"
      },
      null
    ],
    "python": [
      null,
      null,
      {
        "i": "0",
        "arr[0]": "9",
        "arr[i]": "9"
      },
      {
        "arr": "[1, 2, 3, 5, 8, 9]"
      },
      null,
      {
        "arr[i]": "8",
        "arr[left]": "3",
        "arr[right]": "12",
        "largest": "2"
      },
      {
        "arr[i]": "8",
        "arr[largest]": "8"
      }
    ]
  },
  "SRT_004": {
    "typescript": [
      null,
      null,
      {
        "j": "0",
        "arr[j]": "5",
        "arr[j + 1]": "34",
        "swapped": "false"
      },
      {
        "swapped": "true",
        "remaining passes": "avoided"
      },
      {
        "arr": "[1, 2, 3, 5, 8, 9]"
      }
    ],
    "python": [
      null,
      null,
      {
        "j": "0 to n-i-2",
        "arr[j]": "64",
        "arr[j + 1]": "34",
        "swapped": "false"
      },
      {
        "swapped": "true",
        "optimization": "early exit"
      },
      {
        "arr": "[1, 2, 3, 5, 8, 9]"
      }
    ]
  },
  "SRT_005": {
    "typescript": [
      null,
      null,
      {
        "arr[j]": "5",
        "key": "2",
        "j": "0"
      },
      {
        "j + 1": "0",
        "key": "2",
        "arr": "[5, 5, 8, 1, 9, 3]"
      },
      {
        "arr": "[1, 2, 3, 5, 8, 9]"
      },
      null
    ],
    "python": [
      null,
      null,
      {
        "arr[j]": "5",
        "key": "2",
        "j": "0"
      },
      {
        "j + 1": "0",
        "key": "2",
        "arr": "[5, 5, 8, 1, 9, 3]"
      },
      {
        "arr": "[1, 2, 3, 5, 8, 9]"
      },
      null
    ]
  },
  "SRT_006": {
    "typescript": [
      null,
      null,
      {
        "j": "1 to 4",
        "minIdx": "0",
        "arr[minIdx]": "5"
      },
      {
        "arr[i]": "5",
        "arr[minIdx]": "1",
        "i": "0"
      },
      {
        "arr": "[1, 2, 3, 5, 8, 9]"
      },
      null
    ],
    "python": [
      null,
      null,
      {
        "j": "i+1 to n-1",
        "min_idx": "0",
        "arr[min_idx]": "5"
      },
      {
        "arr[i]": "5",
        "arr[min_idx]": "1",
        "i": "0"
      },
      {
        "arr": "[1, 2, 3, 5, 8, 9]"
      },
      null
    ]
  },
  "SRT_007": {
    "typescript": [
      null,
      null,
      null,
      {
        "count": "[0, 0, 0, 0, 0, 0, 0, 0]",
        "count[num - min]++": "frequency"
      },
      {
        "count[i]": "cumulative sum",
        "count": "[1, 2, 2, 1, 0, 0, 0, 1]"
      },
      {
        "num": "1",
        "count[num - min] - 1": "0",
        "output[0]": "undefined"
      },
      null,
      null
    ],
    "python": [
      null,
      null,
      null,
      {
        "count": "[0, 0, 0, 0, 0, 0, 0, 0]",
        "num - min_val": "offset index"
      },
      {
        "count[i]": "cumulative sum",
        "count": "[1, 2, 2, 1, 0, 0, 0, 1]"
      },
      {
        "num": "1",
        "count[num - min_val] - 1": "0",
        "output[0]": "0"
      },
      null
    ]
  },
  "SRT_008": {
    "typescript": [
      null,
      null,
      null,
      null,
      null,
      null,
      {
        "count": "[0, 0, 0, 1, 0, 0, 0, 0, 0, 0]"
      },
      null,
      {
        "arr": "[123]"
      }
    ],
    "python": [
      null,
      null,
      null,
      null,
      null,
      {
        "exp": "1",
        "digit": "(170 // 1) % 10 = 0",
        "count[0]": "0"
      },
      {
        "count": "[0, 0, 0, 1, 0, 0, 0, 0, 0, 0]"
      },
      {
        "digit": "3",
        "output[position]": "arr[i]"
      },
      {
        "arr": "[123]"
      }
    ]
  },
  "SRT_009": {
    "typescript": [
      null,
      null,
      null,
      {
        "num": "42",
        "bucketIndex": "2",
        "buckets[2]": "[]"
      },
      null,
      null,
      null,
      null
    ],
    "python": [
      null,
      null,
      null,
      {
        "num": "42",
        "bucket_index": "2",
        "buckets[2]": "[]"
      },
      null,
      null,
      {
        "arr": "[25]",
        "key": "element to insert"
      },
      null
    ]
  },
  "SRT_010": {
    "typescript": [
      null,
      null,
      null,
      null,
      null,
      null,
      {
        "left": "0",
        "right": "0"
      },
      null
    ]
  },
  "SRT_011": {
    "typescript": [
      null,
      null,
      null,
      null,
      {
        "arr[j]": "54"
      },
      null,
      null,
      null
    ]
  },
  "SRT_012": {
    "typescript": [
      null,
      {
        "edge": "[1, 0]",
        "adjList[1]": "[]",
        "inDegree[0]": "0"
      },
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ]
  },
  "SEA_001": {
    "typescript": [
      null,
      {
        "left": "0",
        "right": "8"
      },
      {
        "left": "0",
        "right": "8",
        "mid": "4"
      },
      {
        "mid": "4",
        "arr[mid]": "50",
        "target": "40"
      },
      null,
      {
        "arr[mid]": "50",
        "target": "40",
        "right": "8"
      },
      null
    ],
    "python": [
      null,
      {
        "left": "0",
        "right": "8"
      },
      {
        "left": "0",
        "right": "8",
        "mid": "4"
      },
      {
        "mid": "4",
        "arr[mid]": "50",
        "target": "40"
      },
      {
        "arr[mid]": "50",
        "target": "40",
        "left": "0"
      },
      {
        "arr[mid]": "50",
        "target": "40",
        "right": "8"
      },
      {
        "left": "4",
        "right": "3",
        "result": "-1"
      }
    ]
  },
  "SEA_002": {
    "python": [
      null,
      null,
      {
        "i": "0",
        "arr[i]": "4",
        "target": "7"
      },
      {
        "i": "0",
        "checked": "4, 2, 7"
      },
      null
    ]
  },
  "SEA_003": {
    "typescript": [
      null,
      null,
      null,
      null,
      null,
      {
        "start": "1",
        "result": "[]"
      }
    ],
    "python": [
      null,
      null,
      {
        "node": "1",
        "visited": "{}",
        "result": "[]"
      },
      null,
      null,
      null
    ]
  },
  "SEA_004": {
    "typescript": [
      {
        "visited": "{}",
        "queue": "[1]",
        "result": "[]"
      },
      {
        "queue": "[]",
        "queue.length": "3"
      },
      {
        "node": "1",
        "queue": "[]",
        "result": "[1]"
      },
      null,
      {
        "neighbor": "2",
        "visited": "{1, 2, 3, 4, 5}",
        "queue": "[]"
      },
      null
    ],
    "python": [
      null,
      null,
      {
        "node": "1",
        "queue": "deque([2, 3])",
        "result": "[]"
      },
      null,
      {
        "neighbor": "2",
        "visited": "{1}",
        "queue": "deque([3, 2])"
      },
      null
    ]
  },
  "SEA_005": {
    "typescript": [
      null,
      null,
      {
        "prev": "0",
        "curr": "0",
        "target": "13",
        "arr[curr]": "1"
      },
      {
        "prev": "0",
        "arr[prev]": "1",
        "target": "13",
        "result": "-1"
      },
      {
        "prev": "4",
        "curr": "8",
        "target": "13",
        "i": "4",
        "arr[10]": "21"
      },
      {
        "i": "5",
        "arr[i]": "11",
        "target": "10",
        "result": "-1"
      },
      null
    ],
    "python": [
      null,
      null,
      {
        "prev": "0",
        "curr": "0",
        "target": "13",
        "arr[curr]": "1"
      },
      {
        "prev": "0",
        "arr[prev]": "1",
        "target": "13",
        "result": "-1"
      },
      {
        "prev": "4",
        "curr": "8",
        "target": "13",
        "i": "8→9→10",
        "arr[10]": "21"
      },
      {
        "i": "4",
        "arr[i]": "9",
        "target": "13",
        "result": "-1"
      },
      null
    ]
  },
  "SEA_006": {
    "typescript": [
      null,
      {
        "low": "0",
        "high": "9",
        "arr[low]": "10",
        "arr[high]": "100",
        "target": "70"
      },
      {
        "low": "0",
        "high": "9",
        "arr[5]": "60",
        "target": "70"
      },
      {
        "low": "0",
        "high": "9",
        "arr[low]": "10",
        "arr[high]": "100",
        "target": "70",
        "pos": "5"
      },
      {
        "pos": "4",
        "arr[pos]": "50",
        "target": "55",
        "result": "5"
      },
      null,
      null
    ],
    "python": [
      null,
      {
        "low": "0",
        "high": "9",
        "arr[low]": "10",
        "arr[high]": "100",
        "target": "70"
      },
      {
        "low": "0",
        "high": "9",
        "arr[5]": "60",
        "target": "70"
      },
      {
        "low": "0",
        "high": "9",
        "arr[low]": "10",
        "arr[high]": "100",
        "target": "70",
        "pos": "5"
      },
      {
        "pos": "6",
        "arr[pos]": "70",
        "target": "70",
        "result": "5"
      },
      {
        "arr[pos]": "50",
        "target": "55",
        "new low": "pos + 1 (6)"
      },
      null
    ]
  },
  "SEA_007": {
    "typescript": [
      null,
      null,
      {
        "i": "1",
        "arr[i]": "4",
        "target": "42"
      },
      null,
      {
        "left": "8",
        "right": "14",
        "target": "42"
      },
      {
        "mid": "11",
        "arr[mid]": "79",
        "target": "42",
        "result": "12"
      }
    ],
    "python": [
      {
        "n": "100",
        "arr[0]": "2",
        "target": "42",
        "result": "0"
      },
      null,
      {
        "i": "1",
        "arr[i]": "4",
        "target": "42"
      },
      {
        "range start": "i//2 (8)",
        "range end": "min(i, n-1) (16)",
        "target": "42"
      },
      {
        "left": "8",
        "right": "14",
        "mid": "12",
        "target": "42"
      }
    ]
  },
  "SEA_008": {
    "typescript": [
      null,
      {
        "left": "0",
        "right": "11",
        "mid1": "2",
        "mid2": "6",
        "sections": "[0-2), [2-6), [6-8]"
      },
      {
        "mid1": "3",
        "mid2": "8",
        "arr[mid1]": "20",
        "arr[mid2]": "45",
        "target": "40"
      },
      {
        "target": "40",
        "arr[mid1]": "20",
        "new right": "mid1 - 1 (1)"
      },
      {
        "target": "40",
        "arr[mid2]": "35",
        "new left": "mid2 + 1 (7)"
      },
      {
        "arr[mid1]": "20",
        "target": "40",
        "arr[mid2]": "45",
        "new range": "[3, 5]"
      },
      null
    ],
    "python": [
      null,
      {
        "left": "0",
        "right": "11",
        "mid1": "2",
        "mid2": "6",
        "sections": "[0-2), [2-6), [6-8]"
      },
      {
        "mid1": "3",
        "mid2": "8",
        "arr[mid1]": "20",
        "arr[mid2]": "45",
        "target": "40"
      },
      {
        "target": "40",
        "arr[mid1]": "20",
        "new right": "mid1 - 1 (1)"
      },
      {
        "target": "40",
        "arr[mid2]": "45",
        "new left": "mid2 + 1 (7)"
      },
      {
        "arr[mid1]": "20",
        "target": "40",
        "arr[mid2]": "45",
        "new range": "[3, 5]"
      },
      null
    ]
  },
  "GRA_001": {
    "typescript": [
      null,
      null,
      {
        "currentDist": "0",
        "u": "0",
        "pq": "[[0,0]]"
      },
      null,
      {
        "distances[v]": "4",
        "pq": "[]"
      },
      null
    ],
    "python": [
      null,
      null,
      null,
      {
        "current_dist": "0",
        "distances[u]": "0"
      },
      null,
      {
        "distances[v]": "Infinity",
        "pq": "[]"
      },
      {
        "distances": "[0, 3, 1, 4]"
      }
    ]
  },
  "GRA_002": {
    "python": [
      null,
      null,
      null,
      {
        "u": "1",
        "v": "3",
        "weight": "5",
        "cycle_detected": "true"
      },
      null,
      {
        "distances": "[0, 4, 1, 3]"
      }
    ]
  },
  "GRA_003": {
    "python": [
      null,
      null,
      null,
      {
        "i": "3",
        "j": "3",
        "k": "0"
      },
      null,
      {
        "dist": "[[0,3,5,6],[5,0,2,3],[3,6,0,1],[2,5,7,0]]"
      }
    ]
  },
  "GRA_004": {
    "typescript": [
      {
        "n": "4",
        "parent": "[0, 1, 2, 3, 4]",
        "rank": "[0, 0, 0, 0, 0]"
      },
      {
        "edges": "[[2,3,4],[0,3,5],[0,2,6],[0,1,10],[1,3,15]]"
      },
      null,
      null,
      null,
      {
        "rootX": "2",
        "rootY": "3",
        "cycle detected": "false"
      },
      null,
      null
    ],
    "python": [
      null,
      null,
      null,
      null,
      null,
      null,
      {
        "u": "0",
        "v": "1",
        "weight": "1",
        "mst_weight": "0"
      },
      {
        "mst_weight": "19"
      }
    ]
  },
  "GRA_005": {
    "typescript": [
      null,
      null,
      null,
      null,
      {
        "v": "1",
        "edgeWeight": "10",
        "pq": "[]"
      },
      null
    ],
    "python": [
      null,
      null,
      {
        "visited[u]": "false",
        "continue": "false"
      },
      {
        "visited[0]": "false",
        "mst_weight": "0"
      },
      {
        "v": "1",
        "edge_weight": "2",
        "pq": "[]"
      },
      {
        "mst_weight": "19",
        "visited": "[true, true, true, true]"
      }
    ]
  },
  "GRA_006": {
    "typescript": [
      null,
      {
        "pq": "[[8,0,0,0]]",
        "start": "[0, 0]",
        "h(start)": "6"
      },
      null,
      null,
      {
        "key": "0,0",
        "visited": "{}"
      },
      null,
      null
    ],
    "python": [
      {
        "goal": "[4, 4]",
        "h(2, 2)": "4"
      },
      {
        "pq": "[(6, 0, 0, 0)]",
        "start": "[0, 0]",
        "h(start)": "6"
      },
      null,
      {
        "current": "(4, 4)",
        "goal": "[4, 4]",
        "cost": "0"
      },
      {
        "x, y": "(2, 3)",
        "visited": "{}"
      },
      null,
      null
    ]
  },
  "GRA_007": {
    "typescript": [
      null,
      null,
      null,
      null,
      {
        "at": "2",
        "ids[at]": "0",
        "low[at]": "0",
        "scc": "[2, 1, 0]"
      },
      null,
      null
    ],
    "python": [
      null,
      {
        "at": "0",
        "ids[0]": "-1",
        "low[0]": "0",
        "stack": "[]"
      },
      null,
      {
        "low[at]": "2",
        "low[to]": "0",
        "min(low[at], low[to])": "0"
      },
      {
        "at": "2",
        "ids[at]": "2",
        "low[at]": "0",
        "scc": "[2, 1, 0]"
      },
      {
        "i": "0",
        "ids[i]": "0"
      },
      null
    ]
  },
  "GRA_008": {
    "typescript": [
      null,
      {
        "v": "0",
        "visited[0]": "false",
        "stack": "[]"
      },
      {
        "graph[0]": "[1]",
        "transposed[1]": "[0]",
        "transposed[2]": "[0]"
      },
      {
        "sccs": "[]",
        "visited": "[false, false, false, false, false, false]"
      },
      null,
      {
        "v": "0",
        "visited[0]": "true",
        "sccs": "[]"
      },
      null
    ],
    "python": [
      null,
      {
        "v": "0",
        "visited[0]": "false",
        "stack": "[]"
      },
      {
        "graph[0]": "[1]",
        "transposed[1]": "[0]",
        "transposed[2]": "[0]"
      },
      {
        "sccs": "[]",
        "visited": "[false, false, false, false, false, false]"
      },
      {
        "v": "5",
        "scc": "[0, 1, 2]"
      },
      {
        "i": "2",
        "visited[2]": "false"
      },
      {
        "v": "5",
        "visited[0]": "true",
        "sccs": "[]"
      },
      {
        "sccs": "[]"
      }
    ]
  },
  "GRA_009": {
    "typescript": [
      null,
      {
        "edge": "[0, 1]",
        "graph[0]": "[]",
        "inDegree[1]": "0"
      },
      {
        "queue": "[0, 2]",
        "inDegree": "[0, 1, 1, 2]"
      },
      {
        "u": "0",
        "result": "[]"
      },
      null,
      null
    ],
    "python": [
      {
        "n": "4",
        "graph": "[[], [], [], [], []]",
        "in_degree": "[0, 0, 0, 0, 0]"
      },
      {
        "u": "0",
        "v": "1",
        "graph[0]": "[]",
        "in_degree[1]": "0"
      },
      {
        "queue": "deque([0, 2])",
        "in_degree": "[0, 1, 1, 2]"
      },
      null,
      {
        "u": "2",
        "result": "[]"
      },
      {
        "v": "3",
        "in_degree[1]": "1",
        "queue": "deque([2, 1])"
      },
      {
        "len(result)": "5",
        "n": "4",
        "valid": "True"
      }
    ]
  },
  "GRA_010": {
    "typescript": [
      null,
      null,
      null,
      null,
      null,
      {
        "i": "0",
        "visited[2]": "false"
      },
      null
    ],
    "python": [
      null,
      {
        "v": "0",
        "visited[0]": "false",
        "rec_stack[0]": "false"
      },
      {
        "neighbor": "1",
        "visited[1]": "false"
      },
      {
        "neighbor": "0",
        "rec_stack[0]": "true",
        "cycle": "True"
      },
      null,
      {
        "i": "0",
        "visited[2]": "true"
      },
      null
    ]
  },
  "GRA_011": {
    "typescript": [
      null,
      null,
      null,
      {
        "v": "1",
        "colors[v]": "1",
        "queue": "[]"
      },
      null,
      {
        "i": "0",
        "colors[i]": "-1"
      },
      null
    ],
    "python": [
      null,
      {
        "start": "0",
        "colors[0]": "-1",
        "queue": "deque([0])"
      },
      null,
      null,
      {
        "colors[u]": "1",
        "colors[v]": "0",
        "conflict": "True"
      },
      {
        "i": "0",
        "colors[i]": "0"
      },
      {
        "return": "True",
        "colors": "[0, 1, 0, 1]"
      }
    ]
  },
  "GRA_012": {
    "typescript": [
      null,
      null,
      null,
      null,
      {
        "next": "B",
        "stack": "[A, C, A, B, C]"
      },
      {
        "stack": "[]",
        "path": "[C, B, A, C, A]"
      },
      null
    ],
    "python": [
      null,
      null,
      null,
      null,
      {
        "next_vertex": "B",
        "stack": "[A]"
      },
      {
        "stack": "[A, C, A, B, C]",
        "path": "[]"
      },
      {
        "path": "[C, B, A, C, A]"
      }
    ]
  },
  "GRA_013": {
    "typescript": [
      null,
      null,
      {
        "next": "0",
        "residual[node][next]": "7",
        "minFlow": "Infinity"
      },
      {
        "flow": "10",
        "residual[node][next]": "3",
        "residual[next][node]": "4"
      },
      {
        "flow": "10",
        "visited": "[true, true, true, false]"
      },
      null,
      null,
      null
    ],
    "python": [
      null,
      {
        "node": "0",
        "target": "3",
        "min_flow": "Infinity"
      },
      {
        "node": "0",
        "visited[0]": "false"
      },
      {
        "next_node": "2",
        "residual[node][next_node]": "7",
        "min_flow": "Infinity"
      },
      {
        "flow": "10",
        "residual[node][next_node]": "3",
        "residual[next_node][node]": "4"
      },
      {
        "flow": "10",
        "visited": "[true, true, true, false]"
      },
      {
        "flow": "6",
        "break": "True"
      },
      {
        "max_flow": "26"
      }
    ]
  },
  "GRA_014": {
    "typescript": [
      null,
      {
        "parent": "[0, 1, 2, 3]",
        "rank": "[0, 0, 0, 0]"
      },
      {
        "x": "2",
        "parent[3]": "1",
        "root": "0"
      },
      {
        "rootX": "2",
        "rootY": "3",
        "cycle": "true"
      },
      null,
      null,
      null
    ]
  },
  "TRE_001": {
    "python": [
      {
        "value": "10",
        "node": "null"
      },
      {
        "node.value": "current node value",
        "value": "20"
      },
      null,
      {
        "balance": "-1",
        "case": "Left-Left"
      },
      {
        "balance": "-1",
        "case": "Right-Right"
      },
      {
        "balance": "-1",
        "case": "Left-Right"
      },
      {
        "balance": "-1",
        "case": "Right-Left"
      },
      null
    ]
  },
  "TRE_004": {
    "python": [
      {
        "start": "0",
        "tree[node]": "arr[start]"
      },
      null,
      null,
      null,
      null,
      null,
      null,
      {
        "idx": "1",
        "tree[node]": "new value"
      }
    ]
  },
  "TRE_005": {
    "python": [
      {
        "originalIndex": "0-based",
        "index": "0"
      },
      {
        "operation": "index += index & (-index)",
        "delta": "3"
      },
      null,
      {
        "queryIndex": "0-based",
        "index": "5"
      },
      null,
      null,
      null
    ]
  },
  "TRE_006": {
    "python": [
      {
        "node": "root",
        "word": "apple"
      },
      null,
      null,
      {
        "is_end_of_word": "True",
        "word": "apple"
      },
      {
        "word": "apple",
        "found": "checking path"
      },
      null,
      {
        "prefix": "app",
        "exists": "path traversable"
      },
      null
    ]
  },
  "TRE_008": {
    "python": [
      null,
      {
        "operation": "go left",
        "stack": "[]"
      },
      {
        "current": "null",
        "operation": "visit node"
      },
      null,
      null,
      null,
      null,
      null
    ]
  },
  "DP_001": {
    "python": [
      null,
      {
        "n": "10",
        "result": "1"
      },
      {
        "n": "10",
        "memo": "{}"
      },
      {
        "n": "10",
        "memo[5]": "5"
      },
      null
    ]
  },
  "DP_003": {
    "python": [
      null,
      {
        "num": "5",
        "tails": "[]",
        "pos": "1"
      },
      {
        "num": "10",
        "tails": "[]",
        "pos": "0"
      },
      {
        "num": "9",
        "pos": "0",
        "tails[1]": "3"
      },
      null
    ]
  },
  "DP_005": {
    "python": [
      null,
      {
        "i": "5",
        "coins": "[1, 2, 5]"
      },
      {
        "coin": "1",
        "i": "1",
        "dp[i]": "12"
      },
      null
    ]
  },
  "GRE_001": {
    "typescript": [
      null,
      {
        "activities": "[{\"start\":1,\"finish\":3},{\"start\":2,\"finish\":5},{\"start\":4,\"finish\":7},{\"start\":1,\"finish\":8},{\"start\":5,\"finish\":9}]"
      },
      {
        "selected": "[{\"start\":1,\"finish\":3}]",
        "lastFinish": "-Infinity"
      },
      null,
      null,
      null
    ],
    "python": [
      null,
      null,
      null,
      {
        "selected": "[]",
        "last_finish": "-Infinity"
      },
      {
        "selected": "[[1,3],[4,7]]"
      }
    ]
  },
  "GRE_002": {
    "typescript": [
      null,
      null,
      {
        "heap": "[]"
      },
      null,
      null,
      null,
      {
        "codes": "{c: 0, a: 10, b: 11}"
      }
    ],
    "python": [
      null,
      null,
      null,
      null,
      null,
      null,
      {
        "codes": "{}"
      }
    ]
  },
  "GRE_003": {
    "typescript": [
      null,
      {
        "ratios": "[{\"index\":0,\"ratio\":6,\"value\":60,\"weight\":10},{\"index\":1,\"ratio\":5,\"value\":100,\"weight\":20},{\"index\":2,\"ratio\":4,\"value\":120,\"weight\":30}]"
      },
      null,
      {
        "totalValue": "0",
        "remainingCapacity": "50"
      },
      {
        "taken": "min(weight, remaining)",
        "totalValue": "240"
      },
      null
    ],
    "python": [
      null,
      {
        "ratios": "[[6,60,10],[5,100,20],[4,120,30]]"
      },
      null,
      {
        "remaining_capacity": "50"
      },
      {
        "taken": "min(weight, remaining)",
        "total_value": "0"
      },
      {
        "total_value": "240"
      }
    ]
  },
  "GRE_004": {
    "typescript": [
      null,
      {
        "jobs": "[{\"id\":\"A\",\"profit\":100,\"deadline\":2},{\"id\":\"C\",\"profit\":27,\"deadline\":2},{\"id\":\"D\",\"profit\":25,\"deadline\":1},{\"id\":\"B\",\"profit\":19,\"deadline\":1}]"
      },
      {
        "maxDeadline": "2",
        "slots": "[null, null]"
      },
      null,
      {
        "slot": "1"
      },
      {
        "scheduled": "[{\"id\":\"A\",\"profit\":100,\"deadline\":2},{\"id\":\"C\",\"profit\":27,\"deadline\":2}]",
        "totalProfit": "127"
      },
      null
    ],
    "python": [
      {
        "jobs": "[[\"A\",100,2],[\"B\",19,1],[\"C\",27,2],[\"D\",25,1]]"
      },
      null,
      null,
      null,
      {
        "slots[slot]": "null",
        "scheduled": "[]",
        "total_profit": "0"
      },
      {
        "scheduled": "[[\"A\",100],[\"C\",27]]",
        "total_profit": "127"
      }
    ]
  },
  "BAC_001": {
    "typescript": [
      null,
      null,
      {
        "row": "0",
        "solutions": "updated with board"
      },
      {
        "col": "0"
      },
      null,
      {
        "row": "1"
      },
      null,
      null
    ],
    "python": [
      null,
      {
        "row": "0",
        "solutions": "[]"
      },
      null,
      {
        "board": "[]",
        "cols": "{}",
        "diag1": "{}",
        "diag2": "{}"
      },
      {
        "row": "0"
      },
      {
        "board": "[Q..., ..Q.]",
        "cols": "{0, 2}",
        "diag1": "{0, -1}",
        "diag2": "{0, 3}"
      },
      {
        "solutions": "[[\".Q..\",\"...Q\",\"Q...\",\"..Q.\"],[\"..Q.\",\"Q...\",\"...Q\",\".Q..\"]]"
      }
    ]
  },
  "BAC_002": {
    "typescript": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      {
        "board": "[[\"5\",\"3\",\".\",\".\",\"7\",\".\",\".\",\".\",\".\"],[\"6\",\".\",\".\",\"1\",\"9\",\"5\",\".\",\".\",\".\"],[\".\",\"9\",\"8\",\".\",\".\",\".\",\".\",\"6\",\".\"],[\"8\",\".\",\".\",\".\",\"6\",\".\",\".\",\".\",\"3\"],[\"4\",\".\",\".\",\"8\",\".\",\"3\",\".\",\".\",\"1\"],[\"7\",\".\",\".\",\".\",\"2\",\".\",\".\",\".\",\"6\"],[\".\",\"6\",\".\",\".\",\".\",\".\",\"2\",\"8\",\".\"],[\".\",\".\",\".\",\"4\",\"1\",\"9\",\".\",\".\",\"5\"],[\".\",\".\",\".\",\".\",\"8\",\".\",\".\",\"7\",\"9\"]]"
      }
    ],
    "python": [
      {
        "num": "1"
      },
      null,
      null,
      null,
      null,
      null,
      null,
      {
        "board": "[[\"5\",\"3\",\"1\",\"2\",\"7\",\"4\",\"8\",\".\",\".\"],[\"6\",\".\",\".\",\"1\",\"9\",\"5\",\".\",\".\",\".\"],[\".\",\"9\",\"8\",\".\",\".\",\".\",\".\",\"6\",\".\"],[\"8\",\".\",\".\",\".\",\"6\",\".\",\".\",\".\",\"3\"],[\"4\",\".\",\".\",\"8\",\".\",\"3\",\".\",\".\",\"1\"],[\"7\",\".\",\".\",\".\",\"2\",\".\",\".\",\".\",\"6\"],[\".\",\"6\",\".\",\".\",\".\",\".\",\"2\",\"8\",\".\"],[\".\",\".\",\".\",\"4\",\"1\",\"9\",\".\",\".\",\"5\"],[\".\",\".\",\".\",\".\",\"8\",\".\",\".\",\"7\",\"9\"]]"
      }
    ]
  },
  "BAC_003": {
    "typescript": [
      null,
      null,
      {
        "i": "0"
      },
      null,
      null,
      {
        "current": "[]",
        "used": "{}"
      },
      null
    ],
    "python": [
      null,
      null,
      null,
      {
        "current": "[]",
        "used": "{}"
      },
      null,
      {
        "current": "[1, 2, 3]",
        "used": "{0, 1, 2}"
      },
      {
        "result": "[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]"
      }
    ]
  },
  "BAC_004": {
    "typescript": [
      null,
      {
        "remaining": "7",
        "current": "valid combination"
      },
      null,
      {
        "start": "0",
        "current": "candidate added"
      },
      {
        "remaining": "1"
      },
      {
        "current": "[]"
      },
      null
    ],
    "python": [
      null,
      {
        "remaining": "7",
        "current": "[]"
      },
      {
        "remaining": "7"
      },
      {
        "start": "0",
        "current": "[]"
      },
      {
        "remaining": "7"
      },
      {
        "current": "[2, 2, 2, 2]"
      },
      {
        "result": "[[2,2,3],[7]]"
      }
    ]
  },
  "TWO_001": {
    "typescript": [
      null,
      null,
      {
        "sum": "9"
      },
      null,
      null,
      null
    ],
    "python": [
      null,
      null,
      {
        "current_sum": "17"
      },
      {
        "left": "0"
      },
      {
        "right": "3"
      },
      null
    ]
  },
  "TWO_002": {
    "python": [
      null,
      null,
      null,
      null,
      null,
      {
        "max_water": "49"
      }
    ]
  },
  "TWO_003": {
    "typescript": [
      null,
      null,
      null,
      null,
      {
        "result": "[[-1,-1,2]]",
        "left": "2",
        "right": "5"
      },
      null,
      {
        "result": "[[-1,-1,2],[-1,0,1]]"
      }
    ],
    "python": [
      {
        "nums": "[-1, 0, 1, 2, -1, -4]",
        "result": "[]"
      },
      null,
      null,
      null,
      {
        "result": "[]",
        "left": "1",
        "right": "5"
      },
      null,
      null
    ]
  },
  "SLI_001": {
    "typescript": [
      null,
      null,
      null,
      null,
      {
        "windowSum": "7"
      },
      null,
      null
    ],
    "python": [
      {
        "len(arr)": "array size",
        "k": "3"
      },
      null,
      null,
      {
        "window_sum": "8"
      },
      {
        "max_sum": "8"
      },
      {
        "max_sum": "9"
      }
    ]
  },
  "SLI_002": {
    "typescript": [
      null,
      null,
      {
        "left": "0"
      },
      null,
      {
        "maxLength": "3"
      },
      null
    ],
    "python": [
      null,
      null,
      {
        "left": "0"
      },
      null,
      {
        "max_length": "0"
      },
      {
        "max_length": "3"
      }
    ]
  },
  "SLI_003": {
    "typescript": [
      null,
      null,
      {
        "char": "s[right]",
        "window": "{}"
      },
      {
        "formed": "1"
      },
      {
        "minLen": "6",
        "minWindow": ""
      },
      {
        "window": "{A: 0, D: 1, O: 1, B: 1, E: 1, C: 1}",
        "formed": "2",
        "left": "0"
      },
      null,
      null
    ],
    "python": [
      null,
      null,
      null,
      null,
      {
        "formed": "0"
      },
      {
        "min_len": "Infinity",
        "min_window": ""
      },
      {
        "window[left_char]": "decremented",
        "formed": "3",
        "left": "0"
      },
      {
        "min_window": "BANC"
      }
    ]
  },
  "LIN_001": {
    "typescript": [
      {
        "slow": "{val: 1, next: [object Object]}",
        "fast": "{val: 1, next: [object Object]}"
      },
      null,
      {
        "slow": "{val: 3, next: [object Object]}",
        "fast": "{val: 3, next: [object Object]}"
      },
      null,
      null
    ]
  },
  "LIN_002": {
    "typescript": [
      {
        "dummy": "{val: 0, next: [object Object]}",
        "current": "{val: 0, next: [object Object]}"
      },
      null,
      null,
      null,
      null,
      null,
      null
    ]
  },
  "LIN_003": {
    "typescript": [
      {
        "prev": "null",
        "current": "{val: 1, next: [object Object]}"
      },
      null,
      {
        "next": "{val: 2, next: [object Object]}"
      },
      null,
      {
        "prev": "{val: 3, next: [object Object]}",
        "current": "null"
      },
      null
    ],
    "python": [
      null,
      null,
      null,
      null,
      {
        "prev": "null",
        "current": "next_node"
      },
      null
    ]
  },
  "STK_002": {
    "python": [
      null,
      {
        "stack.append(val)": "added",
        "val": "3"
      },
      null,
      null,
      null,
      null,
      null
    ]
  },
  "STK_003": {
    "typescript": [
      null,
      null,
      {
        "temperatures[i]": "73",
        "temperatures[stack.top]": "previous temp"
      },
      null,
      null,
      null,
      null
    ],
    "python": [
      null,
      null,
      {
        "temperatures[i]": "73",
        "temperatures[stack[-1]]": "previous temp"
      },
      null,
      {
        "result[idx]": "0",
        "days": "difference"
      },
      null,
      {
        "result": "[1, 1, 4, 2, 1, 1, 0, 0]"
      }
    ]
  },
  "HEA_001": {
    "typescript": [
      null,
      null,
      {
        "num": "3",
        "action": "push and heapifyUp"
      },
      null,
      null,
      null
    ]
  },
  "HEA_002": {
    "typescript": [
      null,
      null,
      null,
      {
        "dummy": "{val: 0, next: [object Object]}",
        "current": "{val: 0, next: [object Object]}"
      },
      null,
      null,
      null
    ],
    "python": [
      null,
      null,
      null,
      {
        "min_heap": "[[1,0,\"<ListNode object at 0x184c310>\"],[1,1,\"<ListNode object at 0x185b288>\"],[2,2,\"<ListNode object at 0x184b578>\"]]"
      },
      null,
      null,
      null
    ]
  },
  "HAS_003": {
    "typescript": [
      {
        "capacity": "2",
        "cache": "Map<key, value>",
        "order": "[]"
      },
      null,
      null,
      null,
      null,
      null,
      null
    ]
  },
  "BIT_001": {
    "python": [
      null,
      null,
      null,
      {
        "result": "4"
      }
    ]
  },
  "BIT_002": {
    "python": [
      null,
      null,
      null,
      {
        "result": "[0, 1, 1, 2, 1, 2]"
      }
    ]
  },
  "MAT_001": {
    "typescript": [
      null,
      null,
      null,
      {
        "i": "2",
        "j": "i*i, i*i+i, i*i+2i, ..."
      },
      null,
      null
    ],
    "python": [
      {
        "n": "20"
      },
      null,
      null,
      {
        "i": "2",
        "j": "i*i, i*i+i, i*i+2i, ..."
      },
      null,
      null
    ]
  },
  "MAT_002": {
    "typescript": [
      {
        "a": "48",
        "b": "18"
      },
      {
        "b": "18"
      },
      null,
      {
        "b": "18"
      },
      {
        "a": "48"
      },
      null
    ],
    "python": [
      {
        "a": "48",
        "b": "18"
      },
      {
        "b": "18"
      },
      {
        "a": "48",
        "b": "18"
      },
      null,
      null
    ]
  },
  "MAT_003": {
    "typescript": [
      null,
      null,
      {
        "x": "2",
        "n": "10"
      },
      {
        "n % 2": "1 or 0",
        "result": "1"
      },
      {
        "x": "4"
      },
      null,
      null
    ],
    "python": [
      {
        "exp": "10",
        "return": "1"
      },
      null,
      {
        "x": "2",
        "n": "10"
      },
      {
        "n % 2": "1 or 0",
        "result": "1"
      },
      {
        "x": "2"
      },
      {
        "n": "10"
      },
      null
    ]
  },
  "STR_001": {
    "typescript": [
      null,
      null,
      {
        "i": "0",
        "j": "0"
      },
      {
        "matches": "[]",
        "j": "1"
      },
      {
        "j": "4",
        "i": "4"
      },
      null,
      null
    ],
    "python": [
      null,
      null,
      {
        "i": "0",
        "j": "0"
      },
      {
        "matches": "[]",
        "j": "1"
      },
      {
        "j": "1",
        "i": "1"
      },
      null,
      null
    ]
  },
  "STR_002": {
    "typescript": [
      null,
      null,
      {
        "p": "0",
        "t": "0"
      },
      {
        "p === t": "hash match",
        "matches": "[0]"
      },
      null,
      null
    ],
    "python": [
      null,
      null,
      {
        "p": "0",
        "t": "0"
      },
      {
        "p == t": "hash match",
        "matches": "[]"
      },
      {
        "t": "59"
      },
      null
    ]
  },
  "STR_003": {
    "typescript": [
      null,
      null,
      {
        "mirror": "2*center - i",
        "p[i]": "0"
      },
      {
        "p[i]": "0"
      },
      {
        "center": "1",
        "right": "0"
      },
      {
        "maxLen": "3",
        "maxCenter": "3"
      },
      null
    ],
    "python": [
      null,
      null,
      {
        "mirror": "2*center - i",
        "p[i]": "0"
      },
      {
        "p[i]": "0"
      },
      {
        "center": "0",
        "right": "0"
      },
      {
        "max_len": "0",
        "max_center": "0"
      },
      null
    ]
  },
  "UNI_001": {
    "typescript": [
      null,
      null,
      {
        "rootX": "0",
        "rootY": "1"
      },
      null,
      null,
      null,
      null
    ]
  },
  "UNI_002": {
    "typescript": [
      null,
      null,
      null,
      {
        "u": "0",
        "v": "1",
        "components": "5"
      },
      null
    ],
    "python": [
      null,
      null,
      null,
      {
        "u": "first vertex",
        "v": "second vertex",
        "components": "5"
      },
      null
    ]
  },
  "TRI_001": {
    "typescript": [
      null,
      null,
      {
        "node": "{children: [[\"a\",{\"children\":[],\"isEndOfWord\":false}]], isEndOfWord: false}",
        "char": "a"
      },
      {
        "node": "{children: [], isEndOfWord: true}",
        "return": "isEndOfWord at final node"
      },
      {
        "node": "{children: [[\"a\",{\"children\":[[\"p\",{\"children\":[[\"p\",{\"children\":[[\"l\",\"[object Object]\"]],\"isEndOfWord\":false}]],\"isEndOfWord\":false}]],\"isEndOfWord\":false}]], isEndOfWord: false}",
        "return": "true if path exists"
      }
    ]
  },
  "TRI_002": {
    "typescript": [
      {
        "root": "{children: [[\"o\",{\"children\":[[\"a\",{\"children\":[[\"t\",{\"children\":[[\"h\",\"[object Object]\"]],\"isEndOfWord\":false}]],\"isEndOfWord\":false}]],\"isEndOfWord\":false}],[\"p\",{\"children\":[[\"e\",{\"children\":[[\"a\",{\"children\":[],\"isEndOfWord\":true}]],\"isEndOfWord\":false}]],\"isEndOfWord\":false}],[\"e\",{\"children\":[[\"a\",{\"children\":[[\"t\",{\"children\":[],\"isEndOfWord\":true}]],\"isEndOfWord\":false}]],\"isEndOfWord\":false}],[\"r\",{\"children\":[[\"a\",{\"children\":[[\"i\",{\"children\":[[\"n\",\"[object Object]\"]],\"isEndOfWord\":false}]],\"isEndOfWord\":false}]],\"isEndOfWord\":false}]], isEndOfWord: false}",
        "result": "[]",
        "m": "rows",
        "n": "cols"
      },
      {
        "i": "0",
        "j": "0",
        "char": "o"
      },
      {
        "next": "{children: [[\"a\",{\"children\":[[\"t\",{\"children\":[[\"h\",{\"children\":[],\"isEndOfWord\":true}]],\"isEndOfWord\":false}]],\"isEndOfWord\":false}]], isEndOfWord: false}",
        "newPath": "o"
      },
      null,
      null,
      null,
      {
        "root": "{children: [[\"o\",{\"children\":[],\"isEndOfWord\":false}]], isEndOfWord: false}",
        "node": "{children: [[\"o\",{\"children\":[],\"isEndOfWord\":false}]], isEndOfWord: false}"
      }
    ],
    "python": [
      null,
      {
        "i": "0",
        "j": "0",
        "char": "board[i][j]"
      },
      null,
      null,
      {
        "i": "0",
        "j": "0"
      },
      null,
      null
    ]
  },
  "DAC_001": {
    "typescript": [
      null,
      null,
      null,
      null,
      {
        "i": "left index",
        "j": "right index",
        "result": "[]"
      },
      {
        "result": "[27]"
      },
      null
    ],
    "python": [
      null,
      null,
      null,
      null,
      null,
      {
        "result": "[27]"
      },
      null
    ]
  },
  "DAC_002": {
    "typescript": [
      null,
      null,
      {
        "mid": "3",
        "pYLeft": "[{\"x\":5,\"y\":1},{\"x\":2,\"y\":3},{\"x\":3,\"y\":4},{\"x\":12,\"y\":10},{\"x\":12,\"y\":30}]",
        "pYRight": "[{\"x\":40,\"y\":50}]"
      },
      {
        "dLeft": "min distance in left",
        "dRight": "min distance in right",
        "d": "1.4142135623730951"
      },
      null,
      null,
      null
    ]
  }
};
